# Generated by Django 2.2.5 on 2019-09-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='loc_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.AddField(
            model_name='branch',
            name='br_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='branch',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
